name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v5
      - name: Lint
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.13.3
          args: check
          src: "./rfc1924"
  test:
    name: Testing
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Test with pytest
        run: python -m pytest --doctest-modules
